### ISSUE TITLE
Build fails with "class file for java.lang.AutoCloseable not found"

### ISSUE THREAD

**Issue by boskamp** [foxysoft/idm-extension-rhidmo#1]
Commit 8451bc3658ec646d1f594b01fb18598ae5a3e767 fails to build on Java 1.6 with error message "class file for java.lang.AutoCloseable not found". That is because the Autocloseable interface has only been added in JDK 1.7. The full Maven build log is attached to this issue.

[mvn_log.txt](https://github.com/foxysoft/idm-extension-rhidmo/files/1914234/mvn_log.txt)

**Comment by SietzeRoorda** [comment]
This is probable due to the javax.mail dependency. The version you downloaded must be compiled with JAVA 7 or later. I've downgraded the version from 1.6.0 to 1.5.6 because 1.5.6 is compiled for 1.5.
